---
name: Conventional Commits
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  lint-pull-request:
    name: Lint Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
